---
- name: Add Application Profile and EPGs
  hosts: localhost
  vars_files: immday_vars.yml
  tasks:
  - name: Add a new AP
    aci_ap:
      host: apic1-pod2
      username: "{{ student_username }}"
      password: mysidlab
      validate_certs: no
      tenant: "{{ tenant }}"
      ap: "{{ ap }}"
      description: student lab AP
      state: present
    delegate_to: localhost

  - name: Add a new EPG
    aci_epg:
      host: apic1-pod2
      username: "{{ student_username }}"
      password: mysidlab
      validate_certs: no
      tenant: "{{ tenant }}"
      ap: "{{ ap }}"
      epg: "{{ item }}"
      description: Web Intranet EPG
      bd: "{{ bd }}"
      preferred_group: no
      state: present
    delegate_to: localhost
    with_items:
      "{{ epgs }}"