# Create Required Security Contract
- name: Add contract for web-to-app
  hosts: localhost
  vars_files: immday_vars.yml
  tasks:
  - name: Add a new contract
    aci_contract:
      host: apic1-pod2
      username: "{{ student_username }}"
      password: "{{ student_password }}"
      validate_certs: no
      tenant: "{{ tenant }}"
      contract: web-to-app
      description: Secure Web-to-App
      scope: application-profile
      state: present
    delegate_to: localhost

  - name: Add a new contract subject
    aci_contract_subject:
      host: apic1-pod2
      username: "{{ student_username }}"
      password: "{{ student_password }}"
      validate_certs: no
      tenant: "{{ tenant }}"
      contract: web-to-app
      subject: web-to-app
      description: test
      reverse_filter: yes
      priority: level1
      dscp: unspecified
      state: present
    delegate_to: localhost

  - name: Add a new filter to a tenant
    aci_filter:
      host: apic1-pod2
      username: "{{ student_username }}"
      password: "{{ student_password }}"
      validate_certs: no
      filter: basic_open
      description: Open Filter
      tenant: "{{ tenant }}"
      state: present
    delegate_to: localhost

  - name: Add a filter entry
    aci_filter_entry:
      host: apic1-pod2
      username: "{{ student_username }}"
      password: "{{ student_password }}"
      validate_certs: no
      state: present
      entry: ether_open
      tenant: "{{ tenant }}"
      filter: basic_open
      descr: ether_open
    delegate_to: localhost

  - name: Add a new contract subject to filer binding
    aci_contract_subject_to_filter:
      host: apic1-pod2
      username: "{{ student_username }}"
      password: "{{ student_password }}"
      validate_certs: no
      tenant: "{{ tenant }}"
      contract: web-to-app
      subject: web-to-app
      filter: basic_open
      state: present
    delegate_to: localhost
    
  - name: Add contract to EPG bindings
    aci_epg_to_contract:
      host: apic1-pod2
      username: "{{ student_username }}"
      password: "{{ student_password }}"
      validate_certs: no
      tenant: "{{ tenant }}"
      ap: "{{ ap }}"
      epg: app-A
      contract: web-to-app
      contract_type: consumer
      state: present
    delegate_to: localhost

  - name: Add contract to EPG bindings
    aci_epg_to_contract:
      host: apic1-pod2
      username: "{{ student_username }}"
      password: "{{ student_password }}"
      validate_certs: no
      tenant: "{{ tenant }}"
      ap: "{{ ap }}"
      epg: web-A
      contract: web-to-app
      contract_type: provider
      state: present
    delegate_to: localhost


